name: Build .NET 9 Project

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koden
        uses: actions/checkout@v4

      - name: Installera .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # <- OBS! Detta kräver att .NET 9 SDK finns officiellt eller som preview

      - name: Restore beroenden
        run: dotnet restore

      - name: Bygg projektet
        run: dotnet build --no-restore

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always() # ensures notify runs even if build fails
    steps:
      - name: Send Discord Notification
        run: |
          STATUS=${{ needs.build.result }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \":bell: PR Build finished with status: **$STATUS**\"}" \
               ${{ secrets.DISCORD_HOOK }}

