name: Build .NET 9 Project

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koden
        uses: actions/checkout@v4

      - name: Installera .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Matchar .NET 9 SDK

      - name: Restore dependencies
        run: dotnet restore

      - name: Bygg projektet
        run: dotnet build --no-restore
